title: "Leatile's Portfolio & Blog"
email: leatilekeekae@gmail.com
description: "My portfolio and blog site"
baseurl: "/Digital-Portfolio"
url: "https://marcolivierkeekae-droid.github.io"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag

navbar:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog"
  - title: "About"
    url: "/about"
