title: "Leatile's Portfolio & Blog"
email: leatilekeekae@gmail.com
description: "My portfolio and blog site"
baseurl: "/Digital-Portfolio"
url: "https://marcolivierkeekae-droid.github.io"

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

navbar:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog"
  - title: "About"
    url: "/about"
