title: "Leatile's Portfolio & Blog"
email: leatilekeekae@gmail.com
description: "My portfolio and blog site"
baseurl: "/Digital-Portfolio"
url: "https://marcolivierkeekae-droid.github.io"

remote_theme: pages-themes/minimal@0.2.0
plugins:
  - jekyll-feed

navbar:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog.html"
  - title: "About"
    url: "/about.html"
  - title: "Resume"
    url: "/resume.html"
  - title: "Skills"
    url: "/skills.html"
  - title: "Group Work"
    url: "/groupwork.html"
  - title: "Application"
    url: "/application.html"
  - title: "Email"
    url: "/email.html"
