title: "Leatile's Portfolio"
description: "Personal blog and portfolio site"
remote_theme: pages-themes/minimal
plugins:
  - jekyll-feed
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/style.css"
